extends: ["spectral:oas"]

functionsDir: ./functions/

functions:
  - version-policy

rules:
  paths-kebab-case:
    description: Paths should be kebab-case.
    message: "{{property}} should be kebab-case (lower-case and separated with hyphens)"
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9_]+})+$"
  version-policy:
    description: API version must be specified in the url
    message: 'servers url must have a valid version'
    severity: error
    given: $.servers[*]~
    then:
      function: version-policy
