name: API Linting 

on:
  - pull_request

jobs:
  build:
    name: Run API Linting 
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          # Files that need to be verified
          file_glob: 'resources/api-files/*.yaml'
          #Policies 
          spectral_ruleset: 'resources/rules/.spectral.yaml'
